In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [2]:
%cd /content/drive/Shareddrives/Hannah & Yasmine/東海大學競賽/Notebook/CGAN-regression-master

/content/drive/Shareddrives/Hannah & Yasmine/東海大學競賽/Notebook/CGAN-regression-master


In [3]:
!pip install -r requirements.txt

In [4]:
!wandb off    #local端存取

W&B disabled, running your script from this directory will only write metadata locally.


In [9]:
!python preprocess_dataset.py --dataset IMBD

In [ ]:
!python main.py --config config.json

串流輸出內容已截斷至最後 5000 行。
torch.Size([517, 1])
Epoch 4374, true	ll: -5.2551	mae: 6.8068
tensor([9998.0000,   24.3000,   23.3000,   23.3000,   23.6000,   23.5000,
          23.3000,   23.2000,   23.3000,   26.0500,   23.3000,   23.5000,
          23.2000], device='cuda:0')
torch.Size([517, 200, 1])
torch.Size([517, 1])
Epoch 4379, true	ll: -5.0054	mae: 6.9096
tensor([9998.0000,   24.3000,   23.3000,   23.3000,   23.6000,   23.5000,
          23.3000,   23.2000,   23.3000,   26.0500,   23.3000,   23.5000,
          23.2000], device='cuda:0')
torch.Size([517, 200, 1])
torch.Size([517, 1])
Epoch 4384, true	ll: -5.6182	mae: 7.047
tensor([9998.0000,   24.3000,   23.3000,   23.3000,   23.6000,   23.5000,
          23.3000,   23.2000,   23.3000,   26.0500,   23.3000,   23.5000,
          23.2000], device='cuda:0')
torch.Size([517, 200, 1])
torch.Size([517, 1])
Epoch 4389, true	ll: -6.2779	mae: 6.9702
tensor([9998.0000,   24.3000,   23.3000,   23.3000,   23.6000,   23.5000,
          23.3000,   23.2

In [ ]:
_